# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/python_swak',
                'doc_host': 'https://shadisharba.github.io',
                'git_url': 'https://github.com/shadisharba/python_swak',
                'lib_path': 'python_swak'},
  'syms': {'python_swak.core': {'python_swak.core.foo': ('core.html#foo', 'python_swak/core.py')}}}
